{{ range $name, $config := .Values.features }}
{{- if $config.enabled }}

{{- if not $config.source -}}
  {{- fail (printf "\n\nERROR: Feature '%s' is enabled but missing the 'source' configuration block in values.yaml!" $name) -}}
{{- end -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.common.argocd_namespace }}
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  source:
    {{- toYaml $config.source | nindent 4 }}
    helm:
      releaseName: {{ $name }}
      {{- /* Handling the merged values we discussed earlier */ -}}
      {{- $merged := dict -}}
      {{- $merged := mustMerge $merged ($.Values.common.values | default dict) -}}
      {{- $merged := mustMerge $merged ($config.values | default dict) -}}
      {{- if $merged }}
      valuesObject:
        {{- toYaml $merged | nindent 8 }}
      {{- end }}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ $config.namespace }}
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/externalName
    {{- if $config.ignoreDifferences }}
    {{- toYaml $config.ignoreDifferences | nindent 4 }}
    {{- end }}
{{- end }}
{{ end }}