releaseName: pce-golinks
source:
  targetRevision: 1.0.0-864c710
redirects:
  - from: /map/fort-kinnard
    to: https://portycommunityenergy.wordpress.com/easy-cycle-routes-from-portobello-porty-prom-to-fort-kinnaird
  - from: /map/meadows
    to: https://portycommunityenergy.wordpress.com/easy-cycle-rides-from-portobello-porty-prom-to-the-meadows
  - from: /map/qmu
    to: https://portycommunityenergy.wordpress.com/easy-cycle-rides-from-portobello-porty-prom-to-queen-margaret-university
  - from: /map/leith-links
    to: https://portycommunityenergy.wordpress.com/easy-cycle-rides-to-portobello-porty-prom-to-leith-links
ingress:
  hostname: go.portycommunityenergy.org
