{{- if .Values.dnsConfig | default dict | pluck "enabled" | first }}
apiVersion: tailscale.com/v1alpha1
kind: DNSConfig
metadata:
  name: ts-dns
  namespace: {{ .Release.Namespace }}
spec:
  nameserver:
    image:
      repo: docker.io/tailscale/k8s-nameserver
      tag: unstable
{{- end }}
