releaseName: db
source:
  targetRevision: 0.7.0
cnpg:
  backup:
    destinationPath: "s3://zenith-staging-private/backend-pg-wal"
    endpointURL: "https://s3.eu-central-003.backblazeb2.com"
    externalSecret:
      enabled: true
      vaultSecretName: "zenith-staging-cnpg"
