{{- if .Values.oci.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.oci.objectStorage.secretName }}
  labels:
    app.kubernetes.io/name: velero
spec:
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    name: {{ .Values.oci.objectStorage.secretName }}
    template:
      engineVersion: v2
      data:
        cloud: |
          [default]
          aws_access_key_id={{ "{{ .access_key_id }}" }}
          aws_secret_access_key={{ "{{ .secret_access_key }}" }}
  data:
    - secretKey: access_key_id
      remoteRef:
        key: {{ .Values.oci.objectStorage.accessKeyIdBWSecret | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret_access_key
      remoteRef:
        key: {{ .Values.oci.objectStorage.secretAccessKeyBWSecret | quote }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
