apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calibre-web
  template:
    metadata:
      labels:
        app: calibre-web
    spec:
      containers:
        - name: calibre-web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8083
          env:
            - name: TZ
              value: {{ .Values.env.TZ | quote }}
            - name: PUID
              value: {{ .Values.env.PUID | quote }}
            - name: PGID
              value: {{ .Values.env.PGID | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            - name: library
              mountPath: /calibre-library
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: calibre-web-config
        - name: library
          persistentVolumeClaim:
            claimName: calibre-web-library
