apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-library
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.library.size }}
