env: prod
ociVault:
  vaultOcid: "ocid1.vault.oc1.uk-london-1.eruxsrmlaafja.abwgiljridwbzbxrs2vvay6b6n6x7xhi3ymapbgov36lrqmm7bkxgh3hmnka"
  compartmentOcid: "ocid1.compartment.oc1..aaaaaaaagyawjldswlrq2f2dnsqz2kqlzsvj6mirpcue7oqwzlyuwx7pqjha"
  region: "uk-london-1"
  tenancyOcid: "ocid1.tenancy.oc1..aaaaaaaach2wyrgzdlf65xepx7rsyod6qdm65tx6timbqiecdi2hlsqqnxca"
  userOcid: "ocid1.user.oc1..aaaaaaaaleope6mb4zrkm7hkvdn5drudblateae6d4izpkkquh44xrfqnhsa"
  iamVaultSecretName: "infra-gitlab-prod-oci-credentials"
b2:
  prefix: "cluster04/gitlab-prod"
  vaultSecretName: "gitlab-prod-backups"
