apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-root-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: mysql-root-creds # Used by the MariaDB Operator
  data:
    - secretKey: password
      remoteRef:
        key: "{{ .Values.oci.rootSecretName }}"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None

{{- if .Values.backup.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mysql-backup-b2-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: mysql-backup-b2-credentials
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: {{ .Values.backup.vaultSecretName }}
{{- end }}
