apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitlab-registry-pull
  namespace: registry-auth
  annotations:
    replicator.v1.mittwald.de/replicate-to: {{ .Values.namespaces | join "," }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    name: gitlab-registry-pull
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: '{"auths":{"registry.gitlab.com":{"username":"{{ `{{.username}}` }}","password":"{{ `{{.password}}` }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: "gitlab-registry-username"
    - secretKey: password
      remoteRef:
        key: "gitlab-registry-password"
