{{- if .Values.ghcrNamespaces }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: registry-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: {{ .Values.ghcrNamespaces | join "," | quote }}
      data:
        .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"{{ `{{.username}}` }}","password":"{{ `{{.password}}` }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: "ghcr-zemlab-username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: "ghcr-zemlab-token"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
