{{- if .Values.ocirNamespaces }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ocir-credentials
  namespace: registry-auth
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: ocir-credentials
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: {{ .Values.ocirNamespaces | join "," | quote }}
      data:
        .dockerconfigjson: '{"auths":{"lhr.ocir.io":{"username":"{{ `{{.username}}` }}","password":"{{ `{{.password}}` }}"}}}'
  data:
    - secretKey: username
      remoteRef:
        key: "infra-ocir-pull-username"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: "infra-ocir-pull-token"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
