apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.name }}-{{ .Values.env }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: {{ .Values.description | default (printf "%s (%s) project" .Values.name .Values.env) }}
  destinations:
    - namespace: "{{ .Values.name }}-{{ .Values.env }}"
      server: "https://kubernetes.default.svc"
  sourceNamespaces:
    - gitops
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/danfoster/zem-gitops"
    {{- range .Values.extraSourceRepos }}
    - {{ . | quote }}
    {{- end }}
