apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zenith-staging
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/project
    helm:
      valueFiles:
        - projects/zenith.yaml
      valuesObject:
        env: staging
        cluster: cluster04
        common:
          values:
            ociVault:
              vaultOcid: "ocid1.vault.oc1.uk-london-1.eruxsrmlaafja.abwgiljridwbzbxrs2vvay6b6n6x7xhi3ymapbgov36lrqmm7bkxgh3hmnka"
              compartmentOcid: "ocid1.compartment.oc1..aaaaaaaagyawjldswlrq2f2dnsqz2kqlzsvj6mirpcue7oqwzlyuwx7pqjha"
              region: "uk-london-1"
              tenancyOcid: "ocid1.tenancy.oc1..aaaaaaaach2wyrgzdlf65xepx7rsyod6qdm65tx6timbqiecdi2hlsqqnxca"
              userOcid: "ocid1.user.oc1..aaaaaaaamuizga6i5rbj4oqq23lzphogqc3klld3umok33mh4r67mljiueua"
              credentialSecretName: "zenith-staging-oci-creds"
        services:
          project-common:
            enabled: true
          backend:
            source:
              targetRevision: 0.2.0-rc1
            values:
              cnpg:
                backup:
                  destinationPath: "s3://zenith-staging-private/backend-pg-wal"
                  endpointURL: "https://s3.eu-central-003.backblazeb2.com"
                  externalSecret:
                    enabled: true
                    vaultSecretName: "cluster04-zenith-staging-cnpg"
              ingress:
                hostname: staging.peakstream.app
                className: cloudflare-tunnel
          frontend:
            source:
              targetRevision: 0.2.0-rc1
            values:
              ingress:
                hostname: staging.peakstream.app
                className: cloudflare-tunnel
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
