apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ingress-credentials
spec:
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  data:
    - secretKey: api-token
      remoteRef:
        key: "{{ .Values.externalSecret.remoteRefKey }}"
        property: apiToken
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: account-id
      remoteRef:
        key: "{{ .Values.externalSecret.remoteRefKey }}"
        property: accountId
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: tunnel-name
      remoteRef:
        key: "{{ .Values.externalSecret.remoteRefKey }}"
        property: tunnelName
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
