{{- if .Values.longhorn.defaultBackupStore.backupTarget }}
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: {{ .Release.Namespace }}
spec:
  cron: "0 3 * * *"
  task: backup
  retain: 30
  concurrency: 1
  groups:
    - default
{{- end }}
