{{- if .Values.globals.ghcrAppInstallID }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zem-ghcr-app-key
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    name: zem-ghcr-app-key
  data:
    - secretKey: privateKey
      remoteRef:
        key: "zemlab-ghcr-app-private-key"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
