apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zem-ghcr-helm-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: helm
        name: ghcr-zemlab-apps
        url: ghcr.io/zemlab/apps/charts
        enableOCI: "true"
        githubAppID: "868367"
        githubAppInstallationID: "49174761"
        githubAppPrivateKey: "{{ `{{.githubAppPrivateKey}}` }}"
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: "argo-github-app-private-key"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
