apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zem-gitlab-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: helm
        url: registry.gitlab.com/zemlab/zenith/charts
        enableOCI: "true"
        username: "{{ `{{.username}}` }}"
        password: "{{ `{{.password}}` }}"
  data:
    - secretKey: username
      remoteRef:
        key: "gitlab-registry-username"
    - secretKey: password
      remoteRef:
        key: "gitlab-registry-password"
