apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zem-github-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      data:
        githubAppID: "{{ `{{.githubAppID}}` }}"
        githubAppInstallationID: "{{ `{{.githubAppInstallationID}}` }}"
        githubAppPrivateKey: "{{ `{{.githubAppPrivateKey}}` }}"
        type: git
        url: https://github.com/zemlab
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: "zem-gitops-app-private-key"
    - secretKey: githubAppID
      remoteRef:
        key: "zem-gitops-app-id"
    - secretKey: githubAppInstallationID
      remoteRef:
        key: "zem-gitops-app-installation-id"
