{{- include "project-instance.validate" . -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.name }}-common-{{ .Values.env }}
  namespace: gitops
  labels:
    project: {{ .Values.name }}
    env: {{ .Values.env }}
    role: common
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ include "project-instance.fullName" . }}
  sources:
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      path: apps/infra/zem-project-common
      helm:
        releaseName: project-common-{{ include "project-instance.fullName" . }}
        ignoreMissingValueFiles: true
        valueFiles:
          - $gitops/projects/{{ .Values.name }}/envs/{{ .Values.cluster }}/{{ .Values.env }}.yaml
    - repoURL: {{ .Values.repoURL }}
      targetRevision: {{ .Values.targetRevision }}
      ref: gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "project-instance.fullName" . }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
