{{- include "project-instance.validate" . -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "project-instance.fullName" . }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.name }} ({{ .Values.env }}) project
  destinations:
    - namespace: {{ include "project-instance.fullName" . }}
      server: "https://kubernetes.default.svc"
  sourceNamespaces:
    - gitops
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "https://github.com/zemlab/zem-gitops"
    - "https://github.com/zemlab/apps"
    - "ghcr.io/zemlab/apps/charts"
    - "https://jouve.github.io/charts/"
    {{- range .Values.extraSourceRepos }}
    - {{ . | quote }}
    {{- end }}
    {{- if .Values.extraSourceRepoURL }}
    - {{ .Values.extraSourceRepoURL | quote }}
    {{- end }}
