{{- include "project-instance.validate" . -}}
{{- if .Values.iamVaultSecretName }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "project-instance.fullName" . }}-oci-credentials
  namespace: project-credentials
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    replicator.v1.mittwald.de/replicate-to: {{ include "project-instance.fullName" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: {{ include "project-instance.fullName" . }}-oci-creds
  dataFrom:
    - extract:
        key: {{ .Values.iamVaultSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
