{{- range .Values.namespaces }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-oci-creds
  annotations:
    replicator.v1.mittwald.de/replicate-to: {{ .targetNamespace }}
spec:
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: {{ .name }}-oci-creds
  dataFrom:
    - extract:
        key: {{ .vaultSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
