apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: awx-admin-password-gen
spec:
  length: 24
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.awx.adminPasswordSecretName }}
spec:
  refreshInterval: "0"
  target:
    name: {{ .Values.awx.adminPasswordSecretName }}
    template:
      data:
        password: "{{`{{ .password }}`}}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: awx-admin-password-gen
      rewrite:
        - regexp:
            source: ".*"
            target: "password"
