source:
  repoURL: git@gitlab.com:zemlab/zem-gitops.git
  targetRevision: main
  path: apps/zem-gitlab/zem-gitlab-runner
releaseName: gitlab-runner
ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
      - /spec/externalName
