source:
  repoURL: https://github.com/danfoster/zem-gitops
  targetRevision: main
  path: apps/zem-gitlab/zem-gitlab-runner
releaseName: gitlab-runner
ignoreDifferences:
  - group: ""
    kind: Service
    jsonPointers:
      - /spec/externalName
