releaseName: tools
source:
  targetRevision: 0.0.0-12e066e

image:
  tag: fix-frontend-version-static-env
  pullPolicy: Always

load:
  enabled: true
  dumpKind: full
  allowHost: db-cluster-rw.zenith-staging
  dbSecret: db-cluster-app
  b2ReadCredsSecret: backup-credentials
