releaseName: tools
source:
  targetRevision: 0.0.0-87970c73

image:
  tag: fix-frontend-version-static-env
  pullPolicy: Always

load:
  enabled: true
  dumpKind: full
  allowHost: db-cluster-rw.zenith-staging
  dbSecret: db-cluster-app
  b2ReadCredsSecret: tools-b2-dump-read
  b2ReadCredsVaultSecret: zenith-staging-b2-dump-read
