releaseName: backend
source:
  targetRevision: 0.4.8
database:
  secretName: db-cluster-app
smtp:
  secretName: backend-smtp
  externalSecret:
    enabled: true
    secretStoreName: oci-vault
    vaultSecretName: zenith-prod-email
ingress:
  hostname: my.peakstream.app
  className: cloudflare-tunnel
