apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        common:
          values:
            cluster:
              name: cluster04
        features:
          cloudflare-ingress:
            enabled: true
            values:
              externalSecret:
                remoteRefKey: infra-cloudflare-ingress-cluster04
          ingress-nginx:
            enabled: false
          project-credentials:
            enabled: true
            values:
              namespaces: []
          registry-auth:
            enabled: true
            extraDestinationNamespaces:
              - zenith-staging
              - zenith-prod
              - gitlab-prod
              - zem-internal-prod
            values:
              namespaces:
                - zenith-staging
                - zenith-prod
                - gitlab-prod
                - zem-internal-prod
          cnpg:
            enabled: true
          longhorn:
            enabled: true
            values:
              ingress:
                hostname: longhorn-cluster04
              backup:
                b2AccessKeyIdSecret: "longhorn-backup-cluster04-access-key-id"
                b2SecretAccessKeySecret: "longhorn-backup-cluster04-secret-access-key"
              longhorn:
                defaultBackupStore:
                  backupTarget: "s3://zem-backups-eu@eu-central-003/longhorn-cluster04"
                persistence:
                  recurringJobSelector:
                    jobList: '[{"name":"snapshot-2h","isGroup":false},{"name":"backup-daily","isGroup":false}]'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy
