apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/infra
    helm:
      valuesObject:
        common:
          values:
            cluster:
              name: cluster04
        features:
          cloudflare-ingress:
            enabled: true
            values:
              externalSecret:
                remoteRefKey: infra-cloudflare-ingress-cluster04
          ingress-nginx:
            enabled: false
          project-credentials:
            enabled: true
            values:
              namespaces:
                - name: zem-internal-prod
                  vaultSecretName: infra-zem-internal-prod-oci-credentials
                  targetNamespace: zem-internal-prod
                - name: zenith-staging
                  vaultSecretName: infra-zenith-staging-oci-credentials
                  targetNamespace: zenith-staging
                - name: zenith-prod
                  vaultSecretName: infra-zenith-prod-oci-credentials
                  targetNamespace: zenith-prod
                - name: zem-external-prod
                  vaultSecretName: infra-zem-external-prod-oci-credentials
                  targetNamespace: zem-external-prod
          registry-auth:
            enabled: true
            extraDestinationNamespaces:
              - zenith-staging
              - zenith-prod
              - gitlab-prod
              - zem-internal-prod
            values:
              namespaces:
                - zenith-staging
                - zenith-prod
                - gitlab-prod
                - zem-internal-prod
          cnpg:
            enabled: true
          longhorn:
            enabled: true
            values:
              ingress:
                hostname: longhorn-cluster04
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy
