apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zem-gitlab-git-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: zem-infra
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        type: git
        url: "git@gitlab.com:zemlab"
        sshPrivateKey: "{{ `{{.sshPrivateKey}}` }}"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: "gitlab-gitops-ssh-key"
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
