{{- if .Values.backups.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backup-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: SecretStore
  target:
    name: backup-credentials
  dataFrom:
    - extract:
        key: {{ .Values.b2.vaultSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
{{- end }}
