apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: {{ .Values.ociVault.vaultOcid | quote }}
      region: {{ .Values.ociVault.region | quote }}
      principalType: UserPrincipal
      auth:
        user: {{ .Values.ociVault.userOcid | quote }}
        tenancy: {{ .Values.ociVault.tenancyOcid | quote }}
        secretRef:
          privatekey:
            name: {{ .Values.ociVault.credentialSecretName }}
            key: privateKey
          fingerprint:
            name: {{ .Values.ociVault.credentialSecretName }}
            key: fingerprint
