apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-generator
  namespace: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops
  source:
    repoURL: https://github.com/zemlab/gitops
    targetRevision: main
    path: charts/infra-generator
    helm:
      valuesObject:
        cluster:
          name: cluster01
        repoURL: https://github.com/zemlab/gitops
        targetRevision: main
        manualSync: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
