env: staging
ociVault:
  vaultOcid: "ocid1.vault.oc1.uk-london-1.eruxsrmlaafja.abwgiljridwbzbxrs2vvay6b6n6x7xhi3ymapbgov36lrqmm7bkxgh3hmnka"
  compartmentOcid: "ocid1.compartment.oc1..aaaaaaaagyawjldswlrq2f2dnsqz2kqlzsvj6mirpcue7oqwzlyuwx7pqjha"
  region: "uk-london-1"
  tenancyOcid: "ocid1.tenancy.oc1..aaaaaaaach2wyrgzdlf65xepx7rsyod6qdm65tx6timbqiecdi2hlsqqnxca"
  userOcid: "ocid1.user.oc1..aaaaaaaadk5zqkxw4iawptiphs55rqah4734s2zt3xkh2pwsfbnlkw2fdsdq"
  iamVaultSecretName: "infra-zenith-staging-oci-credentials"
  credentialSecretName: "zenith-staging-oci-creds"
b2:
  prefix: "cluster04/zenith-staging"
  vaultSecretName: "zenith-staging-backups"
extraSourceRepoURL: "registry.gitlab.com/zemlab/zenith/charts"
extraSourceRepos:
  - "https://jouve.github.io/charts/"
