apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops
  namespace: argocd
spec:
  description: GitOps Project
  destinations:
    - namespace: "gitops"
      server: "https://kubernetes.default.svc"
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
    - namespace: "project-credentials"
      server: "https://kubernetes.default.svc"
  sourceNamespaces:
    - gitops
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "git@gitlab.com:zemlab/zem-gitops.git"
