apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-prod
  namespace: gitops
spec:
  project: gitops
  source:
    repoURL: https://github.com/danfoster/zem-gitops
    targetRevision: main
    path: deployments/project
    helm:
      valueFiles:
        - projects/media.yaml
      valuesObject:
        env: prod
        cluster: cluster01
        common:
          values:
            ociVault:
              vaultOcid: "ocid1.vault.oc1.uk-london-1.eruxsrmlaafja.abwgiljridwbzbxrs2vvay6b6n6x7xhi3ymapbgov36lrqmm7bkxgh3hmnka"
              compartmentOcid: "ocid1.compartment.oc1..aaaaaaaagyawjldswlrq2f2dnsqz2kqlzsvj6mirpcue7oqwzlyuwx7pqjha"
              region: "uk-london-1"
              tenancyOcid: "ocid1.tenancy.oc1..aaaaaaaach2wyrgzdlf65xepx7rsyod6qdm65tx6timbqiecdi2hlsqqnxca"
              userOcid: "ocid1.user.oc1..aaaaaaaa5kbwgqunmmichfnysmb2pxa4bpvre7ceup6ecnveleuicu5e7lyq"
              credentialSecretName: "media-prod-oci-creds"
        services:
          project-common:
            enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jsonPointers:
        - /spec/syncPolicy
